[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "nullfox"
version = "0.6.0"
description = "Cross-platform universal file encryption toolkit utilizing optimized native AES-256 and SHA-256 engines."
readme = "README.md"
requires-python = ">=3.7"

authors = [
    { name = "NullFox", email = "pr0zone.gmaing.z@gmail.com" }
]

license = "MIT"

classifiers = [
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "Operating System :: OS Independent",
    "Topic :: Security :: Cryptography",
    "Topic :: Software Development :: Libraries",
    "Development Status :: 4 - Beta",
]

dependencies = [
    "cffi>=1.15.0",
]

[tool.setuptools.packages.find]
include = ["nullfox", "nullfox.*"]

[tool.setuptools.package-data]
"nullfox" = ["*.so", "*.dll"]

[tool.setuptools]
include-package-data = true

[project.urls]
Homepage = "https://github.com/JojoModz/nullfox"
Documentation = "https://github.com/JojoModz/nullfox#readme"
Source = "https://github.com/JojoModz/nullfox"
Issues = "https://github.com/JojoModz/nullfox/issues"